import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :virtualCrypto, VirtualCryptoWeb.Endpoint,
  url: [host: "vcrypto.sumidora.com", port: 80],
  cache_static_manifest: "priv/static/cache_manifest.json"

# Do not print debug messages in production
config :logger, level: :info

# Finally import the config/prod.secret.exs.example which loads secrets
# and configuration from environment variables.

config :virtualCrypto, VirtualCrypto.Notification.Dispatcher,
  children: [VirtualCrypto.Notification.Webhook.CloudflareWorkers]
